name = "DispersiveShallowWater"
uuid = "4ab875f6-b79a-4e28-9745-4f0293954817"
authors = ["Joshua Lampert <joshua.lampert@tuhh.de>"]
version = "0.1.0-pre"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
